name: Docker Build and Push

on:
  push:
    tags:
      - 'v*'

jobs:
  deply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Test with Maven
        run: mvn test -f pom.xml

      - name: Build with Maven (Skip Tests)
        run: mvn clean package -DskipTests=true

      - name: Build Docker Image
        run: docker build -t ghcr.io/aradidaniel/coffeemaker:${{ github.ref_name }} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ghcr.io/aradidaniel/coffeemaker:${{ github.ref_name }}
